name: bpf escape by go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    # You can test your matrix by printing the current Go version

    - name: install update-libbpf
      run: make update-libbpf 

    - name: build
      run: make build
